<?xml version="1.0"?>
<package format="3">
  <name>cooperative_parking_robot</name>
  <version>1.11.3</version>
  <description>ROS 2 Humble 기반 협동 자율 주차 로봇 시스템 (A* + 단방향 ArUco + 천장 CCTV 2대 병합)</description>
  <maintainer email="team@example.com">SW Team</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-serial</exec_depend>
  <exec_depend>python3-flask</exec_depend>
  <exec_depend>python3-werkzeug</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <test_depend>ament_pytest</test_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
